apiVersion: v1
kind: Service
metadata:
  name: open-webui-svc
  namespace: open-webui
spec:
  type: ClusterIP
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080