replicaCount: 1

image:
  repository: docker.stirlingpdf.com/stirlingtools/stirling-pdf
  tag: "2.5.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  - name: SYSTEM_ROOTURIPATH
    value: "/"

livenessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 1

securityContext:
  fsGroup: 1000

resources: {}
