apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizcontroller-deployment
  namespace: wiz-controller
  labels:
    app: wizcontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wizcontroller
  template:
    metadata:
      labels:
        app: wizcontroller
    spec:
      containers:
        - name: wizcontroller
          image: ghcr.io/mitchfen/wiz-controller:latest
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 250Mi
          ports:
            - containerPort: 80