apiVersion: v1
kind: Service
metadata:
  name: wizcontroller-service
  namespace: wiz-controller
spec:
  type: ClusterIP
  selector:
    app: wizcontroller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80