apiVersion: v1
kind: Service
metadata:
  namespace: momentum
  name: momentum-service
spec:
  type: ClusterIP
  selector:
    app: momentum
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80